"""add name to doctors

Revision ID: d2fef7df917b
Revises: f99a08d823f2
Create Date: 2026-07-08 08:47:23.321977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fef7df917b'
down_revision: Union[str, Sequence[str], None] = 'f99a08d823f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.add_column('doctors', sa.Column('name', sa.String(), nullable=True))

    op.execute(
        """
        UPDATE doctors
        SET name = users.email
        FROM users
        WHERE doctors.user_id = users.id
        """
    )

    op.alter_column('doctors', 'name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'name')
    # ### end Alembic commands ###
